send application ID with all calls
MoralisWeb3/Moralis-JS-SDK-v1 pull request #13
Opened 2022-11-01 21:51 UTC by sogunshola

---
name: 'Pull request'
about: A new pull request
---

## New Pull Request

### Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK-v1/blob/main/SECURITY.md).
- [X] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK-v1/blob/main/CODE_STYLE.md)
- [X] I have made corresponding changes to the documentation
- [X] I have updated Typescript definitions when needed

### Issue Description

Related issue: #`FILL_THIS_OUT`

### Solution Description

2022-11-01 23:52 UTC, ErnoW requested changes

2022-11-01 23:52 UTC, ErnoW commented on src/MoralisSolanaApi.js
> +  static Account = {
Changing to uppercase will be a breaking change, please change it to lowercase

2022-11-02 21:02 UTC, sogunshola commented on src/MoralisSolanaApi.js
> +  static Account = {
@ErnoW reminder for this one

2022-11-02 21:53 UTC, ErnoW approved these changes

2022-11-02 21:54 UTC, merged

2022-11-03 10:02 UTC, ErnoW commented
:tada: This PR is included in version 1.12.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/moralis-v1/v/1.12.0)
- [GitHub release](https://github.com/MoralisWeb3/Moralis-JS-SDK-v1/releases/tag/v1.12.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: